# fly.toml app configuration file generated for shade-scale on 2024-08-25T13:14:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shade-scale'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[env]
PHX_HOST = 'shade-scale.fly.dev'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
protocol = "http"
[http_service.checks.headers]
X-Forwarded-Proto = "https"
X-Forwarded-Host = "kobrakai.de"
X-Forwarded-Port = "443"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
